from pages.order_feed_page import *


class TestFeedOrder:
    @allure.title("При клике на заказ откроется всплывающее окно с деталями")
    @allure.description("Корректное отображение деталей заказа")
    def test_order_details_open(self, driver):
        feed_order = FeedOrderPage(driver)
        feed_order.open_main_page()
        feed_order.wait_for_invisibility_preloader()
        feed_order.click_order_feed()
        feed_order.click_top_order()
        element = feed_order.get_order_details()
        assert element.is_displayed()

    @allure.title("Заказы пользователя из раздела «История заказов» отображаются на странице «Лента заказов»")
    @allure.description("Корректное отображение заказов")
    def test_user_orders_history_on_order_feed(self, driver):
        feed_order = FeedOrderPage(driver)
        feed_order.open_main_page()
        feed_order.wait_for_invisibility_preloader()
        feed_order.click_user_profile()
        feed_order.user_login()
        feed_order.wait_for_invisibility_preloader()
        feed_order.drag_element_and_drop()
        feed_order.click_create_order_wait()
        feed_order.close_order()
        feed_order.wait_for_invisibility_element_close_order()
        feed_order.click_user_profile()
        feed_order.wait_for_invisibility_element_order()
        feed_order.click_order_history()
        number_history = feed_order.get_order_number_history()
        feed_order.click_order_feed()
        number_feed = feed_order.get_order_number()
        assert number_history in number_feed

    @allure.title("При создании нового заказа счётчик Выполнено за всё время увеличивается")
    @allure.description("Корректное увеличение счетчика")
    def test_all_orders_number_updated(self, driver):
        feed_order = FeedOrderPage(driver)
        feed_order.open_main_page()
        feed_order.wait_for_invisibility_preloader()
        feed_order.click_user_profile()
        feed_order.user_login()
        feed_order.wait_until_clickable_feed()
        feed_order.click_order_feed()
        number_before = feed_order.get_number_all_orders()
        feed_order.click_constructor()
        feed_order.drag_element_and_drop()
        feed_order.click_create_order_wait()
        feed_order.close_order()
        feed_order.click_order_feed()
        number_after = feed_order.get_number_all_orders()
        assert number_after > number_before

    @allure.title("При создании нового заказа счётчик Выполнено за сегодня увеличивается,")
    @allure.description("Корректное увеличение счетчика")
    def test_current_orders_number_updated(self, driver):
        feed_order = FeedOrderPage(driver)
        feed_order.open_main_page()
        feed_order.wait_for_invisibility_preloader()
        feed_order.click_user_profile()
        feed_order.user_login()
        feed_order.wait_for_invisibility_preloader()
        feed_order.wait_until_clickable_feed()
        feed_order.click_order_feed()
        number_before = feed_order.get_orders_number_current()
        feed_order.click_constructor()
        feed_order.drag_element_and_drop()
        feed_order.click_create_order_wait()
        feed_order.close_order()
        feed_order.wait_for_invisibility_preloader()
        feed_order.click_order_feed()
        feed_order.wait_for_invisibility_element_history()
        number_after = feed_order.get_orders_number_current()
        assert number_after > number_before

    @allure.title("После оформления заказа его номер появляется в разделе В работе")
    @allure.description("Корректное отображение оформленного заказа")
    def test_order_number_in_progress(self, driver):
        feed_order = FeedOrderPage(driver)
        feed_order.open_main_page()
        feed_order.wait_for_invisibility_preloader()
        feed_order.click_user_profile()
        feed_order.user_login()
        feed_order.drag_element_and_drop()
        feed_order.click_create_order_wait()
        feed_order.close_order()
        feed_order.click_order_feed()
        feed_order.wait_order_in_progress()
        number = feed_order.get_order_number_in_progress()
        assert number.is_displayed()
